const data = {
    projects: [
        {
            title: "Uretek",
            url: "http://wwww.uretekusa.com",
            image: "/images/uretek screenshot.PNG",
            alt: "snapshot of Uretek's homepage",
            skills: ["NextJS", "Headless CMS", "React", "Postgres DB"],
        },
        {
            title: "Investors Associated",
            url: "https://investorsassociated.com/",
            image: "/images/IA screenshot.PNG",
            alt: "snapshot of Investors Associated homepage",
            skills: ["Wordpress", "Javascript", "PHP", "SASS"],
        },
        {
            title: "Kelley Electric",
            url: "https://kelleyelectric.com/",
            image: "/images/kelley screenshot.PNG",
            alt: "snapshot of Kelley Electric homepage",
            skills: ["Wordpress", "Javascript", "PHP", "SASS"],
        },
        {
            title: "IPHCA Landing Page",
            url: "http://tellmetherest.com/",
            image: "/images/IPHCA screenshot.PNG",
            alt: "snapshot of IPHCA Covid landing page",
            skills: ["Lottie", "GSAP", "Wordpress", "Javascript", "SASS"],
        },
        {
            title: "Oak Management",
            url: "https://www.oakmgtllc.com/",
            image: "/images/oak management screenshot.PNG",
            alt: "snapshot of oak management homepage",
            skills: ["Wordpress", "Javascript", "PHP", "SASS"],
        },
        {
            title: "DCG Roofing",
            url: "https://dcgroofing.com/",
            image: "/images/DCG screen shot.PNG",
            alt: "snapshot of DCG Roofing homepage",
            skills: ["Wordpress", "Javascript", "PHP", "SASS"],
        },
    ],
    personalProjects: [
        {
            title: "Pool Tracker",
            url: "https://rainbow-bonbon-562421.netlify.app/",
            image: "/images/Pool Tracker.PNG",
            alt: "snapshot of a website that looks like a pool table",
            skills: ["NextJS", "React", "Firebase DB"],
        },
        {
            title: "Backyard Fantasy Football- React",
            url: "https://cerulean-souffle-2ca846.netlify.app/",
            image: "/images/bff-react.PNG",
            alt: "snapshot of a website that looks like a football field",
            skills: ["React", "Custom Python API"],
        },
        {
            title: "Backyard Fantasy Football- React Native",
            url: "https://github.com/bobsport33/Backyard-Fantasy-Football-React-Native",
            image: "/images/bff_app.jpg",
            alt: "snapshot of a mobile app screen",
            skills: ["React Native", "Custom Python API"],
        },
        {
            title: "Target Share Generator",
            url: "https://github.com/bobsport33/target-share-generator",
            image: "/images/target-share-generator.PNG",
            alt: "snapshot of a github repo",
            skills: ["Python"],
        },
        {
            title: "Parralax Test",
            url: "https://bobsport33.github.io/Parallax-Test/",
            image: "/images/parallax test.PNG",
            alt: "snapshot of a website with dog pictures",
            skills: ["React", "GSAP"],
        },
        {
            title: "GSAP Slides Test",
            url: "https://bobsport33.github.io/GSAP-Test/",
            image: "/images/gsap slides test.PNG",
            alt: "snapshot of a website with horizontal slides",
            skills: ["React", "GSAP"],
        },
        {
            title: "Mix-a_Six",
            url: "https://mix-a-six-ts.vercel.app/",
            image: "/images/mix-a-six.PNG",
            alt: "snapshot of a webpage",
            skills: ["NextJS", "TypeScript", "Postgres DB"],
        },
        {
            title: "Treat Reviews By Benny",
            url: "https://treatreviewsbybenny-iq7bza1x0-bobsport33.vercel.app/",
            image: "/images/treat review by benny.PNG",
            alt: "snapshot of a blog webpage",
            skills: ["NextJS", "React"],
        },
    ],
    skills: [
        "React",
        "NextJS",
        "React Native",
        "Typescript",
        "JavaScript",
        "Sass",
        "PHP",
        "Wordpress",
        "Python",
    ],
    bio: "I am a highly skilled web developer. ",
    scrollyText: [
        "Hello, my name is Bob.",
        "Bob is a web developer.",
        "Bob can build your next web project.",
        "See what Bob can do build.",
    ],
};
export default data;
