import Head from "next/head";

import Header from "../components/Header";
import Hero from "../components/Hero";
import ScrollText from "../components/ScollText";
import Projects from "../components/Projects";
import Footer from "../components/Footer";
import Spacer from "../components/Spacer";

export default function Home() {
    return (
        <>
            <Head>
                <title>scroll animation</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <Hero />
                <ScrollText />
                <Projects title="Projects" />
                {/* <Spacer />
                <Projects title="Personal Projects" /> */}
                <Footer />
            </main>
        </>
    );
}
