import Head from "next/head";
import data from "./api/data";

import Header from "../components/Header";
import Hero from "../components/Hero";
import ScrollText from "../components/ScollText";
import Projects from "../components/Projects";
import Footer from "../components/Footer";
import Spacer from "../components/Spacer";
import PersonalProjects from "../components/PersonalProjects";
import About from "../components/About";

export default function Home() {
    return (
        <>
            <Head>
                <title>scroll animation</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />

                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossorigin
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Archivo:wght@400;500;600;700&family=Judson:wght@400;700&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <main>
                <Header />
                <Hero />
                <ScrollText />
                <Projects projects={data.projects} />
                <PersonalProjects />
                <About />
                <Footer />
            </main>
        </>
    );
}
